export const GAME_COPY = {
  en: {
    autoMark: 'Automatic X marks',
    autoMarkDescription: 'Mark impossible cells after placing a cat.',
    backToGame: 'Back to game',
    cat: 'Cat',
    catPlaced: 'A cat found its perfect territory.',
    cellStates: {
      'auto-marked': 'automatically marked',
      cat: 'cat',
      empty: 'empty',
      marked: 'marked',
    },
    chooseLevel: 'Choose a level',
    completionTitle: (fishRemaining: number, hintUsed: boolean) => {
      const assists = 3 - fishRemaining + Number(hintUsed);
      if (assists === 0) return 'Perfect!';
      if (assists === 1) return 'Excellent!';
      return 'Good job!';
    },
    completedLabel: 'Completed',
    completedBody: 'Every cat has a cozy territory of its own.',
    continue: 'Next level',
    currentLevel: 'Current',
    dailyPuzzle: 'Daily Puzzle',
    doubleTap: 'Click once to mark; double-click to place a cat.',
    exitBody: 'Your current board progress will be lost.',
    exitGame: 'Exit game',
    exitTitle: 'Exit this puzzle?',
    fishRemaining: (count: number) => `${count} fish remaining`,
    gameControls: 'Game controls',
    gameModes: 'Game modes',
    gameOver: 'Out of fish',
    gameOverBody: 'The cats need a little more space. Try this board again.',
    gameStatus: 'Game status',
    guideActionBody:
      'Click once to add an X. Double-click a tile—or select Cat—to place a cat.',
    guideActionTitle: 'Mark your deductions',
    guideColorBody:
      'Every connected color territory must contain exactly one cat.',
    guideColorTitle: 'One cat in every color',
    guideColumnBody: 'Each row and column can contain only one cat.',
    guideColumnTitle: 'One cat in each row and column',
    guideLivesBody:
      'An incorrect cat costs one fish. Lose all three and the board restarts.',
    guideLivesTitle: 'Only three chances',
    guideTouchBody:
      'Cats cannot occupy horizontally, vertically, or diagonally adjacent cells.',
    guideTouchTitle: 'Cats cannot be adjacent',
    haptics: 'Haptic feedback',
    hapticsDescription:
      'Use a short vibration for moves and mistakes when supported by your mobile browser.',
    help: 'How to play',
    homeSettings: 'Settings',
    homeSubtitle: 'A cozy Sudoku puzzle for clever cat lovers.',
    hint: 'Hint',
    hintRemaining: (count: number) => `Hint, ${count} remaining`,
    hintUsed: 'A cat showed you where it likes to sit.',
    howToPlay: 'How to play',
    invalid: 'That tile is not safe. You lost a fish.',
    keepPlaying: 'Continue playing',
    language: 'Game language',
    leaderboard: 'Ranking',
    level: 'Level',
    levels: 'Levels',
    localRanking: 'Times ranked on this device',
    mark: 'Mark',
    next: 'Play again',
    nextTutorial: 'Next',
    noScores: 'Complete a puzzle to record your first time.',
    openDaily: 'Open daily challenge',
    openRanking: 'View times ranked on this device',
    playNow: 'Start playing',
    preferences: 'Preferences',
    puzzleBoard: (level: number) => `Level ${level} puzzle board`,
    puzzleCell: (level: number, row: number, column: number, state: string) =>
      `Level ${level}, row ${row}, column ${column}, ${state}`,
    music: 'Background music',
    musicDescription: 'Play the cozy music loop while you solve.',
    reducedMotion: 'Reduce motion',
    reducedMotionDescription: 'Turn off decorative movement and transitions.',
    reset: 'Reset',
    resetBody:
      'The current board and fish will return to their starting state.',
    resetConfirm: 'Start over?',
    resetGame: 'Reset puzzle',
    restart: 'Try again',
    settings: 'Game settings',
    sound: 'Sound effects',
    soundDescription: 'Play gentle sounds for moves and mistakes.',
    totalLevels: '80 logic challenges',
    time: 'Time',
    tutorialProgress: 'Tutorial step',
    undo: 'Undo',
  },
  zh: {
    autoMark: '自动标记叉号',
    autoMarkDescription: '放猫后自动标记不能放猫的格子。',
    backToGame: '返回游戏',
    cat: '猫咪',
    catPlaced: '猫咪找到了自己的专属领地。',
    cellStates: {
      'auto-marked': '已自动标记',
      cat: '已放置猫咪',
      empty: '空白',
      marked: '已标记',
    },
    chooseLevel: '选择关卡',
    completionTitle: (fishRemaining: number, hintUsed: boolean) => {
      const assists = 3 - fishRemaining + Number(hintUsed);
      if (assists === 0) return '完美通关！';
      if (assists === 1) return '出色通关！';
      return '通关成功！';
    },
    completedLabel: '已完成',
    completedBody: '每只猫都找到了互不打扰的舒适领地。',
    continue: '下一关',
    currentLevel: '当前',
    dailyPuzzle: '每日挑战',
    doubleTap: '单击格子标记叉号，双击格子放置猫咪。',
    exitBody: '退出后，当前棋盘进度将不会保留。',
    exitGame: '退出游戏',
    exitTitle: '退出当前游戏？',
    fishRemaining: (count: number) => `还剩 ${count} 条小鱼`,
    gameControls: '游戏操作',
    gameModes: '游戏模式',
    gameOver: '小鱼用完了',
    gameOverBody: '猫咪们需要更多空间，重新试试这一关吧。',
    gameStatus: '游戏状态',
    guideActionBody: '单击格子标记叉号；双击格子或选择“猫咪”来放置猫咪。',
    guideActionTitle: '标记你的推理',
    guideColorBody: '每种颜色领地中只能放一只猫咪。',
    guideColorTitle: '每种颜色一只猫',
    guideColumnBody: '每一行和每一列都只能放一只猫咪。',
    guideColumnTitle: '同行同列各一只猫',
    guideLivesBody: '放错一只猫会失去一条小鱼，失去三条小鱼后需要重来。',
    guideLivesTitle: '只有三次机会',
    guideTouchBody: '任意两只猫咪都不能放在横向、纵向或斜向相邻的格子里。',
    guideTouchTitle: '猫咪不能放在相邻格子',
    haptics: '触感反馈',
    hapticsDescription: '移动端浏览器支持时，为移动或出错提供轻微触觉提示。',
    help: '玩法介绍',
    homeSettings: '游戏设置',
    homeSubtitle: '给聪明猫奴的治愈系数独游戏。',
    hint: '提示',
    hintRemaining: (count: number) => `提示，剩余 ${count} 次`,
    hintUsed: '一只猫咪悄悄告诉了你它喜欢的位置。',
    howToPlay: '玩法介绍',
    invalid: '这个位置不安全，失去一条小鱼。',
    keepPlaying: '继续游戏',
    language: '游戏语言',
    leaderboard: '排行榜',
    level: '关卡',
    levels: '关卡',
    localRanking: '当前设备用时排行榜',
    mark: '标记',
    next: '再玩一次',
    nextTutorial: '下一步',
    noScores: '完成任意棋盘后，这里会记录你的最佳用时。',
    openDaily: '进入每日挑战',
    openRanking: '查看当前设备用时排行榜',
    playNow: '开始游戏',
    preferences: '偏好设置',
    puzzleBoard: (level: number) => `第 ${level} 关棋盘`,
    puzzleCell: (level: number, row: number, column: number, state: string) =>
      `第 ${level} 关，第 ${row} 行，第 ${column} 列，${state}`,
    music: '背景音乐',
    musicDescription: '解题时播放轻松愉悦的背景音乐。',
    reducedMotion: '减少动态效果',
    reducedMotionDescription: '关闭装饰动画和过渡效果。',
    reset: '重置',
    resetBody: '当前棋盘和小鱼状态都会恢复初始值。',
    resetConfirm: '要重新开始吗？',
    resetGame: '确认重置',
    restart: '重新挑战',
    settings: '游戏设置',
    sound: '音效',
    soundDescription: '移动或出错时播放轻柔的反馈音效。',
    totalLevels: '80 个逻辑挑战',
    time: '用时',
    tutorialProgress: '教学步骤',
    undo: '撤销',
  },
} as const;
